# For more information: https://laravel.com/docs/sail
version: '3'
services:
    server:
        hostname: blek
        restart: always
        image: blekii/sail:latest
        volumes:
            - '.:/var/www/html'
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - sail
        depends_on:
            - db
            - redis
    db:
        image: 'postgres'
        restart: always
        environment:
            POSTGRES_ROOT_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            PGDATA: '/var/lib/pgsql/data'
#        ports:
#            - '5432:5432'
        volumes:
            - './db:/var/lib/pgsql/data'
        networks:
            - sail
    redis:
        restart: always
        image: 'redis:alpine'
#        ports:
#            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - './redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s

networks:
    sail:
        driver: bridge
#volumes:
#    sail-pgsql:
#        driver: local
#    sail-redis:
#        driver: local
#    sail-meilisearch:
#        driver: local
